import type { ProductoVista } from './presentacion';

/** Muestra coherente para revisar la pantalla hasta que A-03 entregue la sesión. */
export const PRODUCTOS_FERRETERIA: readonly ProductoVista[] = [
  {
    id: 'd1',
    nombre: 'Taladro percutor 1/2 pulgada',
    descripcion: '650 W, velocidad variable y reversa',
    imagenUrl: '',
    categoria: 'Herramienta eléctrica',
    marca: 'Truper',
    sku: 'TAL-PER-012',
    codigoBarras: '7506240647281',
    precioVentaCentavos: '164990',
    costoUnitarioCentavos: '118025',
    precioMayoreoCentavos: '152900',
    cantidadMinimaMayoreo: '3',
    tipoVenta: 'precio_fijo',
    visibleEnPos: true,
  },
  {
    id: 'd2',
    nombre: 'Cable THW-LS calibre 12',
    descripcion: 'Cobre, rollo abierto; venta por metro',
    imagenUrl: '',
    categoria: 'Material eléctrico',
    marca: 'IUSA',
    sku: 'CAB-THW-12-N',
    codigoBarras: '',
    precioVentaCentavos: '1850',
    costoUnitarioCentavos: '1290',
    precioMayoreoCentavos: '1690',
    cantidadMinimaMayoreo: '100',
    tipoVenta: 'variable_medida',
    visibleEnPos: true,
  },
  {
    id: 'd3',
    nombre: 'Martillo de uña 16 oz',
    descripcion: 'Mango de fibra de vidrio antiderrapante',
    imagenUrl: '',
    categoria: 'Herramienta manual',
    marca: 'Pretul',
    sku: 'MAR-UNA-16',
    codigoBarras: '7506240619127',
    precioVentaCentavos: '28500',
    costoUnitarioCentavos: '19840',
    precioMayoreoCentavos: '',
    cantidadMinimaMayoreo: '',
    tipoVenta: 'precio_fijo',
    visibleEnPos: true,
  },
  {
    id: 'd4',
    nombre: 'Tornillo punta broca 1 pulgada',
    descripcion: 'Cabeza hexagonal, galvanizado',
    imagenUrl: '',
    categoria: 'Tornillería',
    marca: 'Fiero',
    sku: 'TOR-PB-100',
    codigoBarras: '',
    precioVentaCentavos: '180',
    costoUnitarioCentavos: '95',
    precioMayoreoCentavos: '145',
    cantidadMinimaMayoreo: '100',
    tipoVenta: 'precio_fijo',
    visibleEnPos: true,
  },
  {
    id: 'd5',
    nombre: 'Cemento gris CPC 30R 50 kg',
    descripcion: 'Saco de 50 kg para obra general',
    imagenUrl: '',
    categoria: 'Material de construcción',
    marca: 'Cruz Azul',
    sku: 'CEM-GRI-50',
    codigoBarras: '7501723000504',
    precioVentaCentavos: '28500',
    costoUnitarioCentavos: '24950',
    precioMayoreoCentavos: '27200',
    cantidadMinimaMayoreo: '10',
    tipoVenta: 'precio_fijo',
    visibleEnPos: false,
  },
  {
    id: 'd6',
    nombre: 'Disco de corte metal 4 1/2 pulgadas',
    descripcion: '1 mm de espesor, centro 7/8 pulgada',
    imagenUrl: '',
    categoria: 'Abrasivos',
    marca: 'Austromex',
    sku: 'DIS-COR-412',
    codigoBarras: '7501042013834',
    precioVentaCentavos: '3200',
    costoUnitarioCentavos: '2180',
    precioMayoreoCentavos: '2800',
    cantidadMinimaMayoreo: '25',
    tipoVenta: 'precio_fijo',
    visibleEnPos: true,
  },
];
